### ISSUE TITLE
Add more docs?

### ISSUE THREAD

**Issue by ralphcallaway** [Oblongmana/sublime-salesforce-reference#10]
I love this so much for apex, what would make it even sweeter would be adding support for some additional API references, perhaps with configurations so people can choose to include/exclude apis that aren't useful to them 

top contenders
- Visualforce API
- Object / Field Reference
- Lighting API (this is kind of forward looking, i figure at some point I'm going to use lightning more)

**Comment by Oblongmana** [comment]
@ralphcallaway Appreciate the useful ideas as always :D 

There's a PR open at #9 with some great work from @maaaaarco - waiting on a bit more work before it gets merged. The initial approach there is having 3 commands (so 2 new ones) that function just like the current apex reference command
 - `Salesforce Reference - Apex`
 - `Salesforce Reference - Visualforce`
 - `Salesforce Reference - Service Console`

I'm not 100% sure if it's possible (or in fact desirable) to remove commands from the palette through config - but having api-specific caching settings shouldn't be too much of a challenge - indeed that PR seems to include it! Would want to make sure that the user can still run the commands for those APIs ad-hoc, but will take a look at that a bit closer once that PR's in.

Once that PR is complete, I'll definitely look into adding more - it should mostly be a case of just assembling an appropriate scraper for anything new

**Comment by ralphcallaway** [comment]
@Oblongmana with fuzzy searching seems I can't see a reason anyone would care about some extra references that aren't applicable to them ... was more concerned that you might keep just one menu option, and then have to sort through extra reference indices that aren't useful to you, looks like @maaaaarco is doing it up right, can't wait until that's available!

**Comment by maaaaarco** [comment]
@ralphcallaway i think it's done right now ;)
Maybe give it a try!

I added Service Console and Visualforce reference entries. Plugin is easily extensible if we want to add more docs.

**Comment by ralphcallaway** [comment]
sweet! if you'd be game to through up a pre-release version i'd be happy to beta-test

**Comment by Oblongmana** [comment]
Going to have a play with that PR now, will keep you updated

**Comment by Oblongmana** [comment]
@ralphcallaway (and @maaaaarco )

This should now be stable. Currently this includes Apex, Visualforce, and Service Console. 

I've merged it into the `develop` branch, so in order to do some beta-testing, you'll need to:
 - Uninstall `Salesforce Reference` using package control
 - Either:
   - Clone the repo directly into your sublime packages folder (not sure on your OS, so won't give you a path!), and checkout the `develop` branch
   - Clone the repo wherever you like, checkout the `develop` branch, and create a symlink from your sublime packages folder to the repo

For a summary of the changes - see the PR notes in #14 for info. For the draft release notes for 2.0.0, see `messages/2.0.0.txt`

I likely won't be accepting any further PRs for or adding anything further for 2.0.0 - keen to not let it run too far away in size for now. Aiming to release probably on (NZ) Friday 9am - meaning it will be released in time for the US start of day.

Will open an issue for adding the Lightning API for 2.1.0

**Comment by Oblongmana** [comment]
Note that there's a known bug: #16

**Comment by Oblongmana** [comment]
Marking this issue as complete - and I've opened an issue for adding Lightning API at #15 . Feel free to open new issues or PRs for any other doc types you'd like to see!

**Comment by ralphcallaway** [comment]
nice! @Oblongmana you might think about adding a pre-release to get this out here, package control uses semver for this so if you the dev branch with this merged in as 2.0.3-beta1 it'll only get installed for users who've told packagecontrol to download pre-releases for this package 

main thing for me is if I switch to a dev branch I've got to go manual and I don't get any future updates without intervention, if i can do the pre-release i can try out new stuff, but know that when ever it's fully released I'll automatically get it

you can see some examples of this with the [mavesmate st3 plugin](https://github.com/joeferraro/MavensMate-SublimeText/releases)

**Comment by Oblongmana** [comment]
@ralphcallaway Ah, interesting - hadn't dug into beta functionality before. Obviously this plugin uses semver for releases, but I didn't realise you could tack on a beta suffix and have that distributed. Will have to look into that a bit further for next release!
